version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  paddy-auth:
    container_name: paddy-auth
    networks:
      paddy-bridge:
        aliases:
          - paddy.auth.io
    build: .
#    image: ghcr.io/opensrcerer/paddy-auth:master
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - ".env"

  emqx1:
    image: emqx:5.5.0
    container_name: emqx1
    restart: on-failure
    networks:
      paddy-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - "1883:1883"
      - "18083:18083"